version: '3.8'

services:
  # PostgreSQL Database (Production ашиглана)
  postgres:
    image: postgres:15.5
    container_name: los-postgres
    environment:
      POSTGRES_DB: los_db
      POSTGRES_USER: los_user
      POSTGRES_PASSWORD: los_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - los-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U los_user -d los_db"]
      interval: 30s
      timeout: 10s
      retries: 5

  # Redis Cache  
  redis:
    image: redis:7.2-alpine
    container_name: los-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    volumes:
      - redis_data:/data
    networks:
      - los-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5

  # MinIO Object Storage
  minio:
    image: minio/minio:latest
    container_name: los-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - los-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  redis_data:  
  minio_data:

networks:
  los-network:
    driver: bridge
