# ================================================================
# 🏦 LOS Development Environment Configuration
# Location: backend/src/main/resources/application-dev.yml
# Optimized for local development with enhanced features
# ================================================================

server:
  port: 8080
  servlet:
    context-path: /los
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: on_param
    include-exception: false
  compression:
    enabled: true
    mime-types: application/json,text/html,text/xml,text/plain

spring:
  profiles:
    active: dev
    
  # Database Configuration - H2 for development
  datasource:
    url: jdbc:h2:mem:losdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DEFAULT_NULL_ORDERING=HIGH
    driverClassName: org.h2.Driver
    username: sa
    password: 
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 300000
      leak-detection-threshold: 60000
      
  # JPA/Hibernate Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
        jdbc:
          batch_size: 20
        order_inserts: true
        order_updates: true
        
  # H2 Console (for development only)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
        trace: false
        
  # SQL Initialization
  sql:
    init:
      mode: always
      continue-on-error: false
      
  # Redis Configuration (optional for development)
  redis:
    host: localhost
    port: 6379
    database: 0
    timeout: 2000ms
    lettuce:
      pool:
        max-active: 8
        max-idle: 8
        min-idle: 0
    # Disable Redis health check in dev if Redis not available
    
  # Cache Configuration
  cache:
    type: simple
    cache-names:
      - customers
      - loanProducts
      - documents
      - userPermissions
      - applicationCache
      
  # Jackson Configuration
  jackson:
    serialization:
      write-dates-as-timestamps: false
      indent-output: true
      fail-on-empty-beans: false
    deserialization:
      fail-on-unknown-properties: false
      accept-empty-string-as-null-object: true
    default-property-inclusion: non_null
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Ulaanbaatar
    
  # File Upload Configuration
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 50MB
      file-size-threshold: 2KB
      location: ${java.io.tmpdir}
      
  # Mail Configuration (disabled for development)
  mail:
    host: localhost
    port: 1025  # MailHog for testing
    username: 
    password: 
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
          debug: true
            
# Application Specific Configuration
app:
  name: "LOS Development"
  version: "@project.version@"
  description: "Loan Origination System - Development Environment"
  timezone: "Asia/Ulaanbaatar"
  
  # JWT Configuration (relaxed for development)
  jwt:
    enabled: true
    secret: dev-secret-key-for-testing-only-not-for-production-use-min-256-bits
    expiration: 86400 # 24 hours in seconds
    refresh-expiration: 604800 # 7 days in seconds
    issuer: "LOS-DEV"
    
  # File Storage Configuration
  file:
    upload-dir: ./uploads/dev
    max-size: 52428800 # 50MB
    allowed-types:
      - pdf
      - jpg
      - jpeg
      - png
      - doc
      - docx
      - xls
      - xlsx
      - txt
    temp-dir: ${java.io.tmpdir}/los-dev
    
  # Loan Configuration
  loan:
    default-interest-rate: 12.0
    max-loan-amount: 100000000 # 100M MNT
    min-loan-amount: 500000    # 500K MNT
    max-loan-term: 360         # 30 years in months
    min-loan-term: 6           # 6 months
    currency: "MNT"
    
  # Customer Configuration
  customer:
    auto-kyc: false
    welcome-email: false
    default-status: "PENDING_VERIFICATION"
    
  # Notification Configuration
  notification:
    email:
      enabled: false  # Disable for dev
      from: "noreply@los-dev.local"
    sms:
      enabled: false
    push:
      enabled: false
      
  # External Services Configuration (all disabled for dev)
  external:
    credit-bureau:
      enabled: false
    payment-gateway:
      enabled: false
    document-verification:
      enabled: false
    social-insurance:
      enabled: false
      
  # Development Tools
  dev:
    data-loader:
      enabled: true
      load-sample-data: true
      sample-customers: 50
      sample-loans: 100
    debug:
      enabled: true
      log-sql: true
      log-transactions: true
      log-security: true
    hot-reload:
      enabled: true
    test-endpoints:
      enabled: true
      
  # Security Configuration (relaxed for development)
  security:
    cors:
      enabled: true
      allowed-origins:
        - "http://localhost:3000"
        - "http://localhost:3001"
        - "http://127.0.0.1:3000" 
        - "http://127.0.0.1:3001"
        - "http://localhost:8080"
      allowed-methods: "*"
      allowed-headers: "*"
      allow-credentials: true
      max-age: 3600
    csrf:
      enabled: false
    rate-limiting:
      enabled: false
      
# Logging Configuration
logging:
  level:
    com.company.los: DEBUG
    org.springframework.security: DEBUG
    org.springframework.web: INFO
    org.springframework.data: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.springframework.cache: DEBUG
    root: INFO
  pattern:
    console: "%clr(%d{yyyy-MM-dd HH:mm:ss.SSS}){faint} %clr(%5p) %clr(${PID:- }){magenta} %clr(---){faint} %clr([%15.15t]){faint} %clr(%-40.40logger{39}){cyan} %clr(:){faint} %m%n%wEx"
    file: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: logs/los-dev.log
    max-size: 100MB
    max-history: 7
    
# Management/Actuator Configuration
management:
  endpoints:
    web:
      exposure:
        include: "*"
      base-path: /actuator
      cors:
        allowed-origins: "*"
        allowed-methods: "GET,POST"
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
    info:
      enabled: true
    metrics:
      enabled: true
    loggers:
      enabled: true
    configprops:
      enabled: true
    env:
      enabled: true
      show-values: always
    beans:
      enabled: true
    mappings:
      enabled: true
  health:
    redis:
      enabled: false  # Disable if Redis not available
    db:
      enabled: true
    diskspace:
      enabled: true
      threshold: 100MB
    mail:
      enabled: false
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: true
      mode: full
  metrics:
    export:
      simple:
        enabled: true
        
# Development specific properties
debug: true
trace: false

# Spring Boot Dev Tools
spring.devtools:
  restart:
    enabled: true
    additional-paths: src/main/java
  livereload:
    enabled: true
    port: 35729
  remote:
    secret: los-dev-secret